---
title: 백엔드 API 호출 시 에러 핸들링과 함수
createdAt: 2023. 08. 21
---

백엔드 API를 호출할 때 에러 핸들링은 필수다. 그런데 막상 에러 핸들링을 하려 하면 어떻게 해야 할 지 감이 잘 잡히지 않는다. 어떻게 해야 효율적이고 가독성이 좋게 구현할 수 있을까?

나의 경험을 떠올려보자면, 회원가입의 이메일 중복 체크 API를 호출하는 기능을 구현하던 중 에러 핸들링을 하려고 다음과 같이 작성했다.

```tsx
export async function checkEmail(email: string) {
  try {
    const response = await fetch(emailCheckURL, { 
      method: 'POST',
      body: { email }
    });

    return response.status === 200;
  } catch (error) {
    return false;
  }
}
```

위 코드의 문제점은 다음과 같다.

1. 실제로는 서버에서 어떤 에러가 발생했는지 유저에게 전달해야 하는데 boolean 값을 return 하므로 그러지 못 한다.
2. 에러 status에 따라 내부적으로 핸들링해야 할 것들이 달라질 수 있다. 401 에러와 404 에러, 500 에러에 대해 각각 다른 조치를 취해야 하지 않을까?
3. 같은 API를 호출하지만 다른 동작을 원하는 경우에는 어떻게 처리할까?

비단 API 호출 뿐 아니라 다른 코드들에도 적용되는 이야기인데, 하나의 함수에서 너무 많은 것들을 하려 하면 복잡도도 높아지고, 추후 코드 수정 시 return 타입 등 함수의 구조가 바뀌면 사용하는 쪽에서도 전부 수정해줘야 하는 대참사가 일어나기 십상이다.

위 코드에서는 이메일 중복 체크 API를 호출하고, 에러 핸들링까지 하려 하니 함수의 복잡도가 높아졌고 확장성도 나빠졌다.

`checkEmail()` 함수에서는 API 호출만 하고 response 만 return 한 다음 사용하는 부분에서 에러를 핸들링 해보자.

```TypeScript
export async function checkEmail(email: string) {
  return fetch(emailCheckURL, { 
    method: 'POST',
    body: { email }
  });
}

/* 사용 시 */

try {
  const response = await checkEmail();
  /* ... */
} catch (error) {
  /* ... */
}
```

처음 코드에서 `try-catch` 문을 밖으로 빼낸 것 밖에 없어 보이지만 그래도 이제는 서버에서 발생한 에러를 유저에게 전달할 수도 있고 사용하는 부분에서 에러를 핸들링하니 확장성이 좋아졌다.

여기서 조금만 더 가독성을 높여보자. `try-catch`나 `then-catch`를 사용하는 부분(특히 컴포넌트)에서 사용하면 가독성이 나빠질 수 있다고 생각한다. 김밥을 안말고 펼쳐놓은 느낌..?

다음과 같이 별도의 에러 핸들링 함수를 작성하면 어떨까?

```TypeScript
export const fetchWithHandler = async (
  fetchFn: (...args: any[]) => Promise<Response>,
  {
    onSuccess,
    onError,
  }: {
    onSuccess: (response?: Response) => void;
    onError: (error?: unknown) => void;
  },
) => {
  try {
    const response = await fetchFn();
    onSuccess(response);
  } catch (error) {
    onError(error);
  }
};

/* 사용 시 */

await fetchWithHandler(
  async () => checkEmail(email),
  {
    onSuccess: () => {
      /* ... */
    },
    onError: () => {
      /* ... */
    },
  },
);
```

`fetchFn` 파라미터로 fetch 함수를 전달받고, `onSuccess`와 `onError` 콜백 함수를 전달받아 에러를 핸들링하는 함수를 작성해보았다.

에러 핸들링을 하는 방법에는 여러 가지가 있겠지만 이처럼 별도의 함수를 통해 처리하는 것도 하나의 방법이 될 수 있을 것이다.
